### ISSUE TITLE
Readme.md has unclear environment variables

### ISSUE THREAD

**Issue by bavery22** [iotbzh/YoMo#1]
The README.md has XDT_SDK_BOOTSTRAP which is pretty clear. However, it also has XDT_DIR and XDT_SDK.  How should these be set?  Ignoring XDT_DIR and setting XDT_SDK to XDT_SDK_BOOTSTRAP allowed me to pull in the native and target packages for m3ulcb.   Is this the intended structure?

**Comment by ronan22** [comment]
XDT_DIR and XDT_SDK are two variable define inside the AGL docker image.

#env | grep XDT_DIR
XDT_DIR=/xdt
#env | grep XDT_SDK
XDT_SDK=/xdt/sdk

You can set XDT_DIR and XDT_SDK to any path you want.
